(function () {
  "use strict";

  window.CARD_FONTS = [
    "Cinzel",
    "Cormorant Garamond",
    "Dancing Script",
    "Hachi Maru Pop",
    "Kaisei Decol",
    "M PLUS 1p Black",
    "Noto Sans Runic",
    "Oxanium",
    "Prata",
    "Yeseva One",
    "Zen Kurenaido",
    "Zen Maru Gothic",
  ];

  window.CARD_FRAMES = [
    { id: "01-black-champagne-gold", name: "シャンパンゴールド", src: "./assets/frames/01_black_champagne_gold.png" },
    { id: "01-full-black-champagne-gold", name: "シャンパンゴールド（フル）", src: "./assets/frames/01_full_black_champagne_gold.png" },
    { id: "02-black-crown", name: "クラウン", src: "./assets/frames/02_black_crown.png" },
    { id: "02-full-black-crown", name: "クラウン（フル）", src: "./assets/frames/02_full_black_crown.png" },
    { id: "03-black-rose", name: "ローズ", src: "./assets/frames/03_black_rose.png" },
    { id: "03-full-black-rose", name: "ローズ（フル）", src: "./assets/frames/03_full_black_rose.png" },
    { id: "04-black-diamond", name: "ダイヤモンド", src: "./assets/frames/04_black_diamond.png" },
    { id: "04-full-black-diamond", name: "ダイヤモンド（フル）", src: "./assets/frames/04_full_black_diamond.png" },
    { id: "05-black-chandelier", name: "シャンデリア", src: "./assets/frames/05_black_chandelier.png" },
    { id: "05-full-black-chandelier", name: "シャンデリア（フル）", src: "./assets/frames/05_full_black_chandelier.png" },
    { id: "06-black-champagne", name: "シャンパン", src: "./assets/frames/06_black_champagne.png" },
    { id: "06-full-black-champagne", name: "シャンパン（フル）", src: "./assets/frames/06_full_black_champagne.png" },
    { id: "07-black-bordeaux-velvet", name: "ボルドーベルベット", src: "./assets/frames/07_black_bordeaux_velvet.png" },
    { id: "07-full-black-bordeaux-velvet", name: "ボルドーベルベット（フル）", src: "./assets/frames/07_full_black_bordeaux_velvet.png" },
    { id: "08-black-royal-blue", name: "ロイヤルブルー", src: "./assets/frames/08_black_royal_blue.png" },
    { id: "08-full-black-royal-blue", name: "ロイヤルブルー（フル）", src: "./assets/frames/08_full_black_royal_blue.png" },
    { id: "09-black-purple-smoke", name: "パープルスモーク", src: "./assets/frames/09_black_purple_smoke.png" },
    { id: "09-full-black-purple-smoke", name: "パープルスモーク（フル）", src: "./assets/frames/09_full_black_purple_smoke.png" },
    { id: "10-black-emerald", name: "エメラルド", src: "./assets/frames/10_black_emerald.png" },
    { id: "10-full-black-emerald", name: "エメラルド（フル）", src: "./assets/frames/10_full_black_emerald.png" },
    { id: "11-black-silver-city", name: "シルバーシティ", src: "./assets/frames/11_black_silver_city.png" },
    { id: "11-full-black-silver-city", name: "シルバーシティ（フル）", src: "./assets/frames/11_full_black_silver_city.png" },
    { id: "12-black-platinum-white", name: "プラチナホワイト", src: "./assets/frames/12_black_platinum_white.png" },
    { id: "12-full-black-platinum-white", name: "プラチナホワイト（フル）", src: "./assets/frames/12_full_black_platinum_white.png" },
    { id: "13-black-art-deco", name: "アールデコ", src: "./assets/frames/13_black_art_deco.png" },
    { id: "13-full-black-art-deco", name: "アールデコ（フル）", src: "./assets/frames/13_full_black_art_deco.png" },
    { id: "14-black-baroque", name: "バロック", src: "./assets/frames/14_black_baroque.png" },
    { id: "14-full-black-baroque", name: "バロック（フル）", src: "./assets/frames/14_full_black_baroque.png" },
    { id: "15-black-gothic", name: "ゴシック", src: "./assets/frames/15_black_gothic.png" },
    { id: "15-full-black-gothic", name: "ゴシック（フル）", src: "./assets/frames/15_full_black_gothic.png" },
    { id: "16-black-feather", name: "フェザー", src: "./assets/frames/16_black_feather.png" },
    { id: "16-full-black-feather", name: "フェザー（フル）", src: "./assets/frames/16_full_black_feather.png" },
    { id: "17-black-playing-cards", name: "プレイングカード", src: "./assets/frames/17_black_playing_cards.png" },
    { id: "17-full-black-playing-cards", name: "プレイングカード（フル）", src: "./assets/frames/17_full_black_playing_cards.png" },
    { id: "18-black-moonlit-night", name: "月夜", src: "./assets/frames/18_black_moonlit_night.png" },
    { id: "18-full-black-moonlit-night", name: "月夜（フル）", src: "./assets/frames/18_full_black_moonlit_night.png" },
    { id: "19-black-neon", name: "ネオン", src: "./assets/frames/19_black_neon.png" },
    { id: "19-full-black-neon", name: "ネオン（フル）", src: "./assets/frames/19_full_black_neon.png" },
    { id: "20-black-vip-room", name: "VIPルーム", src: "./assets/frames/20_black_vip_room.png" },
    { id: "20-full-black-vip-room", name: "VIPルーム（フル）", src: "./assets/frames/20_full_black_vip_room.png" },
    { id: "cabaret-full-01-rose-gold-bijou", name: "キャバクラ・フル｜ローズゴールド×ビジュー", src: "./assets/frames/cabaret/full_01_rose_gold_bijou.png" },
    { id: "cabaret-full-02-pink-neon-mirror", name: "キャバクラ・フル｜ピンクネオン×ミラー", src: "./assets/frames/cabaret/full_02_pink_neon_mirror.png" },
    { id: "cabaret-full-03-burgundy-gold-drape", name: "キャバクラ・フル｜ボルドー×ゴールドドレープ", src: "./assets/frames/cabaret/full_03_burgundy_gold_drape.png" },
    { id: "cabaret-full-04-purple-silver-crystal", name: "キャバクラ・フル｜パープル×シルバークリスタル", src: "./assets/frames/cabaret/full_04_purple_silver_crystal.png" },
    { id: "cabaret-full-05-champagne-bubbles", name: "キャバクラ・フル｜シャンパンゴールド×泡きらめき", src: "./assets/frames/cabaret/full_05_champagne_bubbles.png" },
    { id: "cabaret-full-06-pearl-white-gold", name: "キャバクラ・フル｜パールホワイト×ゴールド", src: "./assets/frames/cabaret/full_06_pearl_white_gold.png" },
    { id: "cabaret-full-07-rose-pink-lace", name: "キャバクラ・フル｜ローズピンク×レース", src: "./assets/frames/cabaret/full_07_rose_pink_lace.png" },
    { id: "cabaret-full-08-lavender-bijou", name: "キャバクラ・フル｜ラベンダー×ビジュー", src: "./assets/frames/cabaret/full_08_lavender_bijou.png" },
    { id: "cabaret-full-09-aqua-crystal", name: "キャバクラ・フル｜アクアブルー×クリスタル", src: "./assets/frames/cabaret/full_09_aqua_crystal.png" },
    { id: "cabaret-full-10-light-blue-silver", name: "キャバクラ・フル｜ライトブルー×シルバー", src: "./assets/frames/cabaret/full_10_light_blue_silver.png" },
    { id: "cabaret-full-11-royal-blue-pearl", name: "キャバクラ・フル｜ロイヤルブルー×パール", src: "./assets/frames/cabaret/full_11_royal_blue_pearl.png" },
    { id: "cabaret-full-12-sapphire-pale-gold", name: "キャバクラ・フル｜サファイアブルー×淡金", src: "./assets/frames/cabaret/full_12_sapphire_pale_gold.png" },
    { id: "cabaret-full-13-navy-ice-glow", name: "キャバクラ・フル｜ネイビー×アイスグロウ", src: "./assets/frames/cabaret/full_13_navy_ice_glow.png" },
    { id: "cabaret-full-14-feather-glitter", name: "キャバクラ・フル｜フェザー×グリッター", src: "./assets/frames/cabaret/full_14_feather_glitter.png" },
    { id: "cabaret-full-15-flower-jewelry", name: "キャバクラ・フル｜フラワー×ジュエリー", src: "./assets/frames/cabaret/full_15_flower_jewelry.png" },
    { id: "cabaret-full-16-mirror-acrylic-light", name: "キャバクラ・フル｜ミラー×アクリルライト", src: "./assets/frames/cabaret/full_16_mirror_acrylic_light.png" },
    { id: "cabaret-full-17-perfume-curves", name: "キャバクラ・フル｜香水瓶風曲線装飾", src: "./assets/frames/cabaret/full_17_perfume_curves.png" },
    { id: "cabaret-full-18-lace-glass-reflection", name: "キャバクラ・フル｜レース×ガラス反射", src: "./assets/frames/cabaret/full_18_lace_glass_reflection.png" },
    { id: "cabaret-full-19-drape-pearl-neon", name: "キャバクラ・フル｜ドレープ×パールネオン", src: "./assets/frames/cabaret/full_19_drape_pearl_neon.png" },
    { id: "cabaret-full-20-luxury-mix", name: "キャバクラ・フル｜総合ラグジュアリーミックス", src: "./assets/frames/cabaret/full_20_luxury_mix.png" },
    { id: "cabaret-light-01-fine-bijou-line", name: "キャバクラ・ライト｜細ビジューライン", src: "./assets/frames/cabaret/light_01_fine_bijou_line.png" },
    { id: "cabaret-light-02-soft-pink-neon-line", name: "キャバクラ・ライト｜淡ピンクネオンライン", src: "./assets/frames/cabaret/light_02_soft_pink_neon_line.png" },
    { id: "cabaret-light-03-pearl-white-fine-edge", name: "キャバクラ・ライト｜パールホワイト細縁", src: "./assets/frames/cabaret/light_03_pearl_white_fine_edge.png" },
    { id: "cabaret-light-04-rose-gold-fine-ornament", name: "キャバクラ・ライト｜ローズゴールド細装飾", src: "./assets/frames/cabaret/light_04_rose_gold_fine_ornament.png" },
    { id: "cabaret-light-05-lavender-glow", name: "キャバクラ・ライト｜ラベンダーグロウ", src: "./assets/frames/cabaret/light_05_lavender_glow.png" },
    { id: "cabaret-light-06-aqua-clear", name: "キャバクラ・ライト｜アクアクリア", src: "./assets/frames/cabaret/light_06_aqua_clear.png" },
    { id: "cabaret-light-07-light-blue-silver-reflection", name: "キャバクラ・ライト｜ライトブルー×シルバー細反射", src: "./assets/frames/cabaret/light_07_light_blue_silver_reflection.png" },
    { id: "cabaret-light-08-royal-blue-fine-line", name: "キャバクラ・ライト｜ロイヤルブルー細ライン", src: "./assets/frames/cabaret/light_08_royal_blue_fine_line.png" },
    { id: "cabaret-light-09-sapphire-sparkle", name: "キャバクラ・ライト｜サファイアきらめき", src: "./assets/frames/cabaret/light_09_sapphire_sparkle.png" },
    { id: "cabaret-light-10-champagne-particles", name: "キャバクラ・ライト｜シャンパン粒子", src: "./assets/frames/cabaret/light_10_champagne_particles.png" },
    { id: "cabaret-light-11-fine-lace-edge", name: "キャバクラ・ライト｜レース細縁", src: "./assets/frames/cabaret/light_11_fine_lace_edge.png" },
    { id: "cabaret-light-12-feather-light", name: "キャバクラ・ライト｜フェザーライト", src: "./assets/frames/cabaret/light_12_feather_light.png" },
    { id: "cabaret-light-13-petal-glow", name: "キャバクラ・ライト｜花びらグロウ", src: "./assets/frames/cabaret/light_13_petal_glow.png" },
    { id: "cabaret-light-14-mirror-line", name: "キャバクラ・ライト｜ミラーライン", src: "./assets/frames/cabaret/light_14_mirror_line.png" },
    { id: "cabaret-light-15-glass-drops", name: "キャバクラ・ライト｜ガラスドロップ", src: "./assets/frames/cabaret/light_15_glass_drops.png" },
    { id: "cabaret-light-16-perfume-label-curves", name: "キャバクラ・ライト｜香水ラベル風曲線", src: "./assets/frames/cabaret/light_16_perfume_label_curves.png" },
    { id: "cabaret-light-17-drape-edge", name: "キャバクラ・ライト｜ドレープエッジ", src: "./assets/frames/cabaret/light_17_drape_edge.png" },
    { id: "cabaret-light-18-pearl-neon", name: "キャバクラ・ライト｜パールネオン", src: "./assets/frames/cabaret/light_18_pearl_neon.png" },
    { id: "cabaret-light-19-blue-white-night-glow", name: "キャバクラ・ライト｜青白い夜光フレーム", src: "./assets/frames/cabaret/light_19_blue_white_night_glow.png" },
    { id: "cabaret-light-20-light-mix", name: "キャバクラ・ライト｜総合ライトミックス", src: "./assets/frames/cabaret/light_20_light_mix.png" },
  ];

  window.CARD_TEMPLATES = [
    {
      id: "linen-note",
      name: "リネン・ノート",
      shortName: "シンプル",
      description: "余白を生かし、SSと文章を静かに見せる縦型カード。",
      kind: "simple",
      width: 1200,
      height: 1500,
      slots: [{ x: 150, y: 520, width: 900, height: 570 }],
      swatches: ["#f7f2ea", "#d8a6a1", "#353039"],
      messageBox: { x: 140, y: 1115, width: 920, height: 220, padding: 30, shape: "rounded", color: "#555257", opacity: 0.22 },
      text: {
        headline: { x: 600, y: 92, font: "Cormorant Garamond", size: 76, color: "#9f6770", align: "center", maxWidth: 980 },
        recipient: { x: 600, y: 210, font: "Zen Kurenaido", size: 54, color: "#312d34", align: "center", maxWidth: 980 },
        body: { x: 600, y: 1135, font: "Zen Maru Gothic", size: 33, color: "#312d34", align: "center", maxWidth: 920 },
        signature: { x: 1040, y: 1395, font: "Dancing Script", size: 48, color: "#9f6770", align: "right", maxWidth: 500 },
      },
    },
    {
      id: "blue-bloom",
      name: "ブルー・ブルーム",
      shortName: "エレガント",
      description: "淡い花と細い飾り枠をあしらった横型カード。",
      kind: "elegant",
      width: 1600,
      height: 1100,
      slots: [{ x: 80, y: 160, width: 600, height: 750, angle: -5 }],
      swatches: ["#f8fbfd", "#a9c5d9", "#55748f"],
      messageBox: { x: 735, y: 350, width: 760, height: 390, padding: 36, shape: "rounded", color: "#6e7c87", opacity: 0.18 },
      text: {
        headline: { x: 1110, y: 145, font: "Prata", size: 62, color: "#6b88a4", align: "center", maxWidth: 700 },
        recipient: { x: 1110, y: 250, font: "Kaisei Decol", size: 52, color: "#4e6d88", align: "center", maxWidth: 740 },
        body: { x: 1110, y: 380, font: "Zen Maru Gothic", size: 34, color: "#49657d", align: "center", maxWidth: 720 },
        signature: { x: 1440, y: 900, font: "Zen Kurenaido", size: 48, color: "#5d7690", align: "right", maxWidth: 520 },
      },
    },
    {
      id: "midnight-screen",
      name: "ミッドナイト・スクリーン",
      shortName: "フルスクリーン",
      description: "X・Discord・PC向け。SS全面を使う1920×1080の横長16:9。",
      kind: "fullscreen",
      width: 1920,
      height: 1080,
      slots: [{ x: 0, y: 0, width: 1920, height: 1080 }],
      swatches: ["#171822", "#7e668d", "#efe7dc"],
      messageBox: { x: 90, y: 695, width: 940, height: 250, padding: 38, shape: "rounded", color: "#19191d", opacity: 0.54 },
      text: {
        headline: { x: 96, y: 74, font: "Cinzel", size: 74, color: "#fff8ef", align: "left", maxWidth: 1500 },
        recipient: { x: 98, y: 205, font: "Zen Kurenaido", size: 52, color: "#fff8ef", align: "left", maxWidth: 1200 },
        body: { x: 128, y: 733, font: "Zen Maru Gothic", size: 34, color: "#ffffff", align: "left", maxWidth: 864 },
        signature: { x: 1810, y: 965, font: "Dancing Script", size: 58, color: "#f4d7bc", align: "right", maxWidth: 700 },
      },
    },
    {
      id: "memory-collage",
      name: "メモリー・コラージュ",
      shortName: "コラージュ",
      description: "3枚のSSをポラロイド風に並べる、思い出重視の縦型。",
      kind: "collage",
      width: 1080,
      height: 1528,
      slots: [
        { x: 530, y: 96, width: 430, height: 400, angle: 5 },
        { x: 82, y: 485, width: 445, height: 420, angle: -5 },
        { x: 515, y: 735, width: 430, height: 400, angle: 4 },
      ],
      swatches: ["#33233e", "#3e817c", "#c9b0d5"],
      messageBox: { x: 70, y: 1190, width: 840, height: 225, padding: 26, shape: "rounded", color: "#242128", opacity: 0.42 },
      text: {
        headline: { x: 80, y: 115, font: "Dancing Script", size: 66, color: "#ffffff", align: "left", maxWidth: 430 },
        recipient: { x: 80, y: 285, font: "Hachi Maru Pop", size: 36, color: "#f4edf7", align: "left", maxWidth: 420 },
        body: { x: 80, y: 1210, font: "Zen Kurenaido", size: 31, color: "#ffffff", align: "left", maxWidth: 780 },
        signature: { x: 995, y: 1415, font: "Dancing Script", size: 48, color: "#ffffff", align: "right", maxWidth: 440 },
      },
    },
    {
      id: "grand-toast",
      name: "グランド・トースト",
      shortName: "華やか",
      description: "ボトルや記念日に似合う、深い色と金の光のカード。",
      kind: "luxury",
      width: 1200,
      height: 1500,
      slots: [{ x: 128, y: 330, width: 944, height: 680 }],
      swatches: ["#241426", "#b78b47", "#f5e8cb"],
      messageBox: { x: 150, y: 1050, width: 900, height: 270, padding: 34, shape: "rounded", color: "#1b151c", opacity: 0.48 },
      text: {
        headline: { x: 600, y: 88, font: "Yeseva One", size: 70, color: "#e2bf78", align: "center", maxWidth: 980 },
        recipient: { x: 600, y: 220, font: "Kaisei Decol", size: 48, color: "#f7ead3", align: "center", maxWidth: 930 },
        body: { x: 600, y: 1060, font: "Zen Maru Gothic", size: 33, color: "#fff9ee", align: "center", maxWidth: 870 },
        signature: { x: 1045, y: 1392, font: "Cormorant Garamond", size: 52, color: "#e5c37e", align: "right", maxWidth: 500 },
      },
    },
    {
      id: "no-template",
      name: "テンプレートなし",
      shortName: "SS＋文字",
      description: "縦型SSの比率と雰囲気を生かし、装飾なしで文字だけを重ねます。",
      kind: "none",
      width: 1200,
      height: 1500,
      slots: [{ x: 0, y: 0, width: 1200, height: 1500 }],
      swatches: ["#252525", "#777777", "#efefef"],
      messageBox: { x: 70, y: 1080, width: 900, height: 250, padding: 30, shape: "rounded", color: "#252529", opacity: 0.45 },
      text: {
        headline: { x: 72, y: 72, font: "Cinzel", size: 62, color: "#ffffff", align: "left", maxWidth: 1020 },
        recipient: { x: 72, y: 185, font: "Zen Kurenaido", size: 48, color: "#ffffff", align: "left", maxWidth: 1020 },
        body: { x: 72, y: 1090, font: "Zen Maru Gothic", size: 33, color: "#ffffff", align: "left", maxWidth: 900 },
        signature: { x: 1110, y: 1390, font: "Dancing Script", size: 52, color: "#ffffff", align: "right", maxWidth: 520 },
      },
    },
  ];
})();
