(function () {
  "use strict";

  window.CARD_FONTS = [
    "Cinzel",
    "Cormorant Garamond",
    "Dancing Script",
    "Hachi Maru Pop",
    "Kaisei Decol",
    "M PLUS 1p Black",
    "Noto Sans Runic",
    "Oxanium",
    "Prata",
    "Yeseva One",
    "Zen Kurenaido",
    "Zen Maru Gothic",
  ];

  window.CARD_TEMPLATES = [
    {
      id: "linen-note",
      name: "リネン・ノート",
      shortName: "シンプル",
      description: "余白を生かし、SSと文章を静かに見せる縦型カード。",
      kind: "simple",
      width: 1200,
      height: 1500,
      slots: [{ x: 150, y: 520, width: 900, height: 570 }],
      swatches: ["#f7f2ea", "#d8a6a1", "#353039"],
      text: {
        headline: { x: 600, y: 92, font: "Cormorant Garamond", size: 76, color: "#9f6770", align: "center", maxWidth: 980 },
        recipient: { x: 600, y: 210, font: "Zen Kurenaido", size: 54, color: "#312d34", align: "center", maxWidth: 980 },
        body: { x: 600, y: 1135, font: "Zen Maru Gothic", size: 33, color: "#312d34", align: "center", maxWidth: 920 },
        signature: { x: 1040, y: 1395, font: "Dancing Script", size: 48, color: "#9f6770", align: "right", maxWidth: 500 },
      },
    },
    {
      id: "blue-bloom",
      name: "ブルー・ブルーム",
      shortName: "エレガント",
      description: "淡い花と細い飾り枠をあしらった横型カード。",
      kind: "elegant",
      width: 1600,
      height: 1100,
      slots: [{ x: 80, y: 160, width: 600, height: 750, angle: -5 }],
      swatches: ["#f8fbfd", "#a9c5d9", "#55748f"],
      text: {
        headline: { x: 1110, y: 145, font: "Prata", size: 62, color: "#6b88a4", align: "center", maxWidth: 700 },
        recipient: { x: 1110, y: 250, font: "Kaisei Decol", size: 52, color: "#4e6d88", align: "center", maxWidth: 740 },
        body: { x: 1110, y: 380, font: "Zen Maru Gothic", size: 34, color: "#49657d", align: "center", maxWidth: 720 },
        signature: { x: 1440, y: 900, font: "Zen Kurenaido", size: 48, color: "#5d7690", align: "right", maxWidth: 520 },
      },
    },
    {
      id: "midnight-screen",
      name: "ミッドナイト・スクリーン",
      shortName: "フルスクリーン",
      description: "SSを全面に使い、余韻のある光と文字を重ねる縦型。",
      kind: "fullscreen",
      width: 1080,
      height: 1350,
      slots: [{ x: 0, y: 0, width: 1080, height: 1350 }],
      swatches: ["#171822", "#7e668d", "#efe7dc"],
      text: {
        headline: { x: 82, y: 90, font: "Cinzel", size: 62, color: "#fff8ef", align: "left", maxWidth: 900 },
        recipient: { x: 82, y: 210, font: "Zen Kurenaido", size: 46, color: "#fff8ef", align: "left", maxWidth: 900 },
        body: { x: 82, y: 940, font: "Zen Maru Gothic", size: 32, color: "#ffffff", align: "left", maxWidth: 820 },
        signature: { x: 990, y: 1240, font: "Dancing Script", size: 52, color: "#f4d7bc", align: "right", maxWidth: 520 },
      },
    },
    {
      id: "memory-collage",
      name: "メモリー・コラージュ",
      shortName: "コラージュ",
      description: "3枚のSSをポラロイド風に並べる、思い出重視の縦型。",
      kind: "collage",
      width: 1080,
      height: 1528,
      slots: [
        { x: 530, y: 96, width: 430, height: 400, angle: 5 },
        { x: 82, y: 485, width: 445, height: 420, angle: -5 },
        { x: 515, y: 735, width: 430, height: 400, angle: 4 },
      ],
      swatches: ["#33233e", "#3e817c", "#c9b0d5"],
      text: {
        headline: { x: 80, y: 115, font: "Dancing Script", size: 66, color: "#ffffff", align: "left", maxWidth: 430 },
        recipient: { x: 80, y: 285, font: "Hachi Maru Pop", size: 36, color: "#f4edf7", align: "left", maxWidth: 420 },
        body: { x: 80, y: 1210, font: "Zen Kurenaido", size: 31, color: "#ffffff", align: "left", maxWidth: 780 },
        signature: { x: 995, y: 1415, font: "Dancing Script", size: 48, color: "#ffffff", align: "right", maxWidth: 440 },
      },
    },
    {
      id: "grand-toast",
      name: "グランド・トースト",
      shortName: "華やか",
      description: "ボトルや記念日に似合う、深い色と金の光のカード。",
      kind: "luxury",
      width: 1200,
      height: 1500,
      slots: [{ x: 128, y: 330, width: 944, height: 680 }],
      swatches: ["#241426", "#b78b47", "#f5e8cb"],
      text: {
        headline: { x: 600, y: 88, font: "Yeseva One", size: 70, color: "#e2bf78", align: "center", maxWidth: 980 },
        recipient: { x: 600, y: 220, font: "Kaisei Decol", size: 48, color: "#f7ead3", align: "center", maxWidth: 930 },
        body: { x: 600, y: 1060, font: "Zen Maru Gothic", size: 33, color: "#fff9ee", align: "center", maxWidth: 870 },
        signature: { x: 1045, y: 1392, font: "Cormorant Garamond", size: 52, color: "#e5c37e", align: "right", maxWidth: 500 },
      },
    },
    {
      id: "no-template",
      name: "テンプレートなし",
      shortName: "SS＋文字",
      description: "装飾を加えず、読み込んだSSと文字だけで仕上げます。",
      kind: "none",
      width: 1200,
      height: 1500,
      slots: [{ x: 0, y: 0, width: 1200, height: 1500 }],
      swatches: ["#252525", "#777777", "#efefef"],
      text: {
        headline: { x: 72, y: 72, font: "Cinzel", size: 62, color: "#ffffff", align: "left", maxWidth: 1020 },
        recipient: { x: 72, y: 185, font: "Zen Kurenaido", size: 48, color: "#ffffff", align: "left", maxWidth: 1020 },
        body: { x: 72, y: 1090, font: "Zen Maru Gothic", size: 33, color: "#ffffff", align: "left", maxWidth: 900 },
        signature: { x: 1110, y: 1390, font: "Dancing Script", size: 52, color: "#ffffff", align: "right", maxWidth: 520 },
      },
    },
  ];
})();
