(function () {
  "use strict";

  window.CARD_FONTS = [
    "Cinzel",
    "Cormorant Garamond",
    "Dancing Script",
    "Hachi Maru Pop",
    "Kaisei Decol",
    "M PLUS 1p Black",
    "Noto Sans Runic",
    "Oxanium",
    "Prata",
    "Yeseva One",
    "Zen Kurenaido",
    "Zen Maru Gothic",
  ];

  window.CARD_FRAMES = [
    { id: "01-black-champagne-gold", name: "シャンパンゴールド", src: "./assets/frames/01_black_champagne_gold.png" },
    { id: "01-full-black-champagne-gold", name: "シャンパンゴールド（フル）", src: "./assets/frames/01_full_black_champagne_gold.png" },
    { id: "02-black-crown", name: "クラウン", src: "./assets/frames/02_black_crown.png" },
    { id: "02-full-black-crown", name: "クラウン（フル）", src: "./assets/frames/02_full_black_crown.png" },
    { id: "03-black-rose", name: "ローズ", src: "./assets/frames/03_black_rose.png" },
    { id: "03-full-black-rose", name: "ローズ（フル）", src: "./assets/frames/03_full_black_rose.png" },
    { id: "04-black-diamond", name: "ダイヤモンド", src: "./assets/frames/04_black_diamond.png" },
    { id: "04-full-black-diamond", name: "ダイヤモンド（フル）", src: "./assets/frames/04_full_black_diamond.png" },
    { id: "05-black-chandelier", name: "シャンデリア", src: "./assets/frames/05_black_chandelier.png" },
    { id: "05-full-black-chandelier", name: "シャンデリア（フル）", src: "./assets/frames/05_full_black_chandelier.png" },
    { id: "06-black-champagne", name: "シャンパン", src: "./assets/frames/06_black_champagne.png" },
    { id: "06-full-black-champagne", name: "シャンパン（フル）", src: "./assets/frames/06_full_black_champagne.png" },
    { id: "07-black-bordeaux-velvet", name: "ボルドーベルベット", src: "./assets/frames/07_black_bordeaux_velvet.png" },
    { id: "07-full-black-bordeaux-velvet", name: "ボルドーベルベット（フル）", src: "./assets/frames/07_full_black_bordeaux_velvet.png" },
    { id: "08-black-royal-blue", name: "ロイヤルブルー", src: "./assets/frames/08_black_royal_blue.png" },
    { id: "08-full-black-royal-blue", name: "ロイヤルブルー（フル）", src: "./assets/frames/08_full_black_royal_blue.png" },
    { id: "09-black-purple-smoke", name: "パープルスモーク", src: "./assets/frames/09_black_purple_smoke.png" },
    { id: "09-full-black-purple-smoke", name: "パープルスモーク（フル）", src: "./assets/frames/09_full_black_purple_smoke.png" },
    { id: "10-black-emerald", name: "エメラルド", src: "./assets/frames/10_black_emerald.png" },
    { id: "10-full-black-emerald", name: "エメラルド（フル）", src: "./assets/frames/10_full_black_emerald.png" },
    { id: "11-black-silver-city", name: "シルバーシティ", src: "./assets/frames/11_black_silver_city.png" },
    { id: "11-full-black-silver-city", name: "シルバーシティ（フル）", src: "./assets/frames/11_full_black_silver_city.png" },
    { id: "12-black-platinum-white", name: "プラチナホワイト", src: "./assets/frames/12_black_platinum_white.png" },
    { id: "12-full-black-platinum-white", name: "プラチナホワイト（フル）", src: "./assets/frames/12_full_black_platinum_white.png" },
    { id: "13-black-art-deco", name: "アールデコ", src: "./assets/frames/13_black_art_deco.png" },
    { id: "13-full-black-art-deco", name: "アールデコ（フル）", src: "./assets/frames/13_full_black_art_deco.png" },
    { id: "14-black-baroque", name: "バロック", src: "./assets/frames/14_black_baroque.png" },
    { id: "14-full-black-baroque", name: "バロック（フル）", src: "./assets/frames/14_full_black_baroque.png" },
    { id: "15-black-gothic", name: "ゴシック", src: "./assets/frames/15_black_gothic.png" },
    { id: "15-full-black-gothic", name: "ゴシック（フル）", src: "./assets/frames/15_full_black_gothic.png" },
    { id: "16-black-feather", name: "フェザー", src: "./assets/frames/16_black_feather.png" },
    { id: "16-full-black-feather", name: "フェザー（フル）", src: "./assets/frames/16_full_black_feather.png" },
    { id: "17-black-playing-cards", name: "プレイングカード", src: "./assets/frames/17_black_playing_cards.png" },
    { id: "17-full-black-playing-cards", name: "プレイングカード（フル）", src: "./assets/frames/17_full_black_playing_cards.png" },
    { id: "18-black-moonlit-night", name: "月夜", src: "./assets/frames/18_black_moonlit_night.png" },
    { id: "18-full-black-moonlit-night", name: "月夜（フル）", src: "./assets/frames/18_full_black_moonlit_night.png" },
    { id: "19-black-neon", name: "ネオン", src: "./assets/frames/19_black_neon.png" },
    { id: "19-full-black-neon", name: "ネオン（フル）", src: "./assets/frames/19_full_black_neon.png" },
    { id: "20-black-vip-room", name: "VIPルーム", src: "./assets/frames/20_black_vip_room.png" },
    { id: "20-full-black-vip-room", name: "VIPルーム（フル）", src: "./assets/frames/20_full_black_vip_room.png" },
  ];

  window.CARD_TEMPLATES = [
    {
      id: "linen-note",
      name: "リネン・ノート",
      shortName: "シンプル",
      description: "余白を生かし、SSと文章を静かに見せる縦型カード。",
      kind: "simple",
      width: 1200,
      height: 1500,
      slots: [{ x: 150, y: 520, width: 900, height: 570 }],
      swatches: ["#f7f2ea", "#d8a6a1", "#353039"],
      messageBox: { x: 140, y: 1115, width: 920, height: 220, padding: 30, shape: "rounded", color: "#555257", opacity: 0.22 },
      text: {
        headline: { x: 600, y: 92, font: "Cormorant Garamond", size: 76, color: "#9f6770", align: "center", maxWidth: 980 },
        recipient: { x: 600, y: 210, font: "Zen Kurenaido", size: 54, color: "#312d34", align: "center", maxWidth: 980 },
        body: { x: 600, y: 1135, font: "Zen Maru Gothic", size: 33, color: "#312d34", align: "center", maxWidth: 920 },
        signature: { x: 1040, y: 1395, font: "Dancing Script", size: 48, color: "#9f6770", align: "right", maxWidth: 500 },
      },
    },
    {
      id: "blue-bloom",
      name: "ブルー・ブルーム",
      shortName: "エレガント",
      description: "淡い花と細い飾り枠をあしらった横型カード。",
      kind: "elegant",
      width: 1600,
      height: 1100,
      slots: [{ x: 80, y: 160, width: 600, height: 750, angle: -5 }],
      swatches: ["#f8fbfd", "#a9c5d9", "#55748f"],
      messageBox: { x: 735, y: 350, width: 760, height: 390, padding: 36, shape: "rounded", color: "#6e7c87", opacity: 0.18 },
      text: {
        headline: { x: 1110, y: 145, font: "Prata", size: 62, color: "#6b88a4", align: "center", maxWidth: 700 },
        recipient: { x: 1110, y: 250, font: "Kaisei Decol", size: 52, color: "#4e6d88", align: "center", maxWidth: 740 },
        body: { x: 1110, y: 380, font: "Zen Maru Gothic", size: 34, color: "#49657d", align: "center", maxWidth: 720 },
        signature: { x: 1440, y: 900, font: "Zen Kurenaido", size: 48, color: "#5d7690", align: "right", maxWidth: 520 },
      },
    },
    {
      id: "midnight-screen",
      name: "ミッドナイト・スクリーン",
      shortName: "フルスクリーン",
      description: "X・Discord・PC向け。SS全面を使う1920×1080の横長16:9。",
      kind: "fullscreen",
      width: 1920,
      height: 1080,
      slots: [{ x: 0, y: 0, width: 1920, height: 1080 }],
      swatches: ["#171822", "#7e668d", "#efe7dc"],
      messageBox: { x: 90, y: 695, width: 940, height: 250, padding: 38, shape: "rounded", color: "#19191d", opacity: 0.54 },
      text: {
        headline: { x: 96, y: 74, font: "Cinzel", size: 74, color: "#fff8ef", align: "left", maxWidth: 1500 },
        recipient: { x: 98, y: 205, font: "Zen Kurenaido", size: 52, color: "#fff8ef", align: "left", maxWidth: 1200 },
        body: { x: 128, y: 733, font: "Zen Maru Gothic", size: 34, color: "#ffffff", align: "left", maxWidth: 864 },
        signature: { x: 1810, y: 965, font: "Dancing Script", size: 58, color: "#f4d7bc", align: "right", maxWidth: 700 },
      },
    },
    {
      id: "memory-collage",
      name: "メモリー・コラージュ",
      shortName: "コラージュ",
      description: "3枚のSSをポラロイド風に並べる、思い出重視の縦型。",
      kind: "collage",
      width: 1080,
      height: 1528,
      slots: [
        { x: 530, y: 96, width: 430, height: 400, angle: 5 },
        { x: 82, y: 485, width: 445, height: 420, angle: -5 },
        { x: 515, y: 735, width: 430, height: 400, angle: 4 },
      ],
      swatches: ["#33233e", "#3e817c", "#c9b0d5"],
      messageBox: { x: 70, y: 1190, width: 840, height: 225, padding: 26, shape: "rounded", color: "#242128", opacity: 0.42 },
      text: {
        headline: { x: 80, y: 115, font: "Dancing Script", size: 66, color: "#ffffff", align: "left", maxWidth: 430 },
        recipient: { x: 80, y: 285, font: "Hachi Maru Pop", size: 36, color: "#f4edf7", align: "left", maxWidth: 420 },
        body: { x: 80, y: 1210, font: "Zen Kurenaido", size: 31, color: "#ffffff", align: "left", maxWidth: 780 },
        signature: { x: 995, y: 1415, font: "Dancing Script", size: 48, color: "#ffffff", align: "right", maxWidth: 440 },
      },
    },
    {
      id: "grand-toast",
      name: "グランド・トースト",
      shortName: "華やか",
      description: "ボトルや記念日に似合う、深い色と金の光のカード。",
      kind: "luxury",
      width: 1200,
      height: 1500,
      slots: [{ x: 128, y: 330, width: 944, height: 680 }],
      swatches: ["#241426", "#b78b47", "#f5e8cb"],
      messageBox: { x: 150, y: 1050, width: 900, height: 270, padding: 34, shape: "rounded", color: "#1b151c", opacity: 0.48 },
      text: {
        headline: { x: 600, y: 88, font: "Yeseva One", size: 70, color: "#e2bf78", align: "center", maxWidth: 980 },
        recipient: { x: 600, y: 220, font: "Kaisei Decol", size: 48, color: "#f7ead3", align: "center", maxWidth: 930 },
        body: { x: 600, y: 1060, font: "Zen Maru Gothic", size: 33, color: "#fff9ee", align: "center", maxWidth: 870 },
        signature: { x: 1045, y: 1392, font: "Cormorant Garamond", size: 52, color: "#e5c37e", align: "right", maxWidth: 500 },
      },
    },
    {
      id: "no-template",
      name: "テンプレートなし",
      shortName: "SS＋文字",
      description: "縦型SSの比率と雰囲気を生かし、装飾なしで文字だけを重ねます。",
      kind: "none",
      width: 1200,
      height: 1500,
      slots: [{ x: 0, y: 0, width: 1200, height: 1500 }],
      swatches: ["#252525", "#777777", "#efefef"],
      messageBox: { x: 70, y: 1080, width: 900, height: 250, padding: 30, shape: "rounded", color: "#252529", opacity: 0.45 },
      text: {
        headline: { x: 72, y: 72, font: "Cinzel", size: 62, color: "#ffffff", align: "left", maxWidth: 1020 },
        recipient: { x: 72, y: 185, font: "Zen Kurenaido", size: 48, color: "#ffffff", align: "left", maxWidth: 1020 },
        body: { x: 72, y: 1090, font: "Zen Maru Gothic", size: 33, color: "#ffffff", align: "left", maxWidth: 900 },
        signature: { x: 1110, y: 1390, font: "Dancing Script", size: 52, color: "#ffffff", align: "right", maxWidth: 520 },
      },
    },
  ];
})();
